### ISSUE TITLE
Missing specification for label lines

### ISSUE THREAD

**Issue by davidhoksza** [LDWLab/RNA2D-data-schema#3]
Not sure if this should be part of the specs, but we might want to be able to specify a polyline (curve) connecting a label with a residue (currently only straight line is supported).

**Comment by CaedenMeade** [comment]
Hello, David. I have made edits to both the validator and XRNA to support polylines. Within "labelLine", properties "x1", "y1", "x2" and "y2", have been replaced by the property "points" which is an array. Each entry in the array is an object which expects properties "x" and "y". Please let me know what you think of this change.

**Comment by davidhoksza** [comment]
I implemented this change to the Traveler output. I currently have only straight lines, but that might change soon :). Thx!
