### ISSUE TITLE
Storing additional information with residues/base pairs

### ISSUE THREAD

**Issue by davidhoksza** [LDWLab/RNA2D-data-schema#4]
In [Traveler](https://github.com/cusbg/traveler/), I need to specify additional information with residues, such as index or the residue in template. I suggest adding an `info` field of type `object` where one could store additional info. Currently, when I add a fields which I need, the validator throws an error:

```
ERROR: Additional properties are not allowed ('info', 'templateResidueName', 'templateNumberingLabel', 'templateResidueIndex' were unexpected)
```

The same might be useful for base pairs?

**Comment by CaedenMeade** [comment]
Hello, David, I have added an "info" object to both nucleotide.json and base-pair.json. Please let me whether this resolves your issue!

**Comment by davidhoksza** [comment]
Works great. Thx.
