### ISSUE TITLE
Add classes to base pairs

### ISSUE THREAD

**Issue by davidhoksza** [LDWLab/RNA2D-data-schema#5]
It would be useful to add `classes` field to the `base-pair`. The reason is that one might want to specify, e.g., width of the line or color; the same way it is currently possible for labels and residues.

**Comment by CaedenMeade** [comment]
Hey, David, I have made this change. It is pushed to GitHub and reflected on XRNA. Please let me know whether this resolves this issue.

**Comment by davidhoksza** [comment]
Works fine. Thx
