### ISSUE TITLE
Having class on the sequence and base-pair level

### ISSUE THREAD

**Issue by davidhoksza** [LDWLab/RNA2D-data-schema#7]
It would be useful to have the ability to specify `class` on the `basePair`, `labels` or `sequence` object. For example, one might want to specify a font for all residues and a different font for all labels. Currently, the font class needs to be specified with each residue/label which takes a lot of space.

**Comment by CaedenMeade** [comment]
Hello, David, I've made a few additions to the rna-molecule schema specification. I added three variables: "classesForSequence", "classesForLabels" and "classesForBasePairs". Note that these variables are separate form the "basePairs", "labels", and "sequence" arrays. These styles are reflected by XRNA. Please let me know if this resolves your issue!

**Comment by davidhoksza** [comment]
Works fine. Thx
