### ISSUE TITLE
Info field with rna-molecule

### ISSUE THREAD

**Issue by davidhoksza** [LDWLab/RNA2D-data-schema#9]
Would it be possible to add the `info` field to the `rna-molecule` node, too? The reason is that in the Traveler output, I need to store information about the positions of the 5' and 3' labels somewhere. Currently, I am storing them as the first and last residue which does not pass the validation because allowed codes are ACGU only.

**Comment by CaedenMeade** [comment]
Hey, David, I have added the info field to rna-molecule nodes. I have also added the following as valid nucleotide symbols: "5", "5'", "3", "3'". Please let me know if this resolves this issue.

**Comment by davidhoksza** [comment]
Works. The Traveler output now produces a valid schema. Thanks!
